### ISSUE TITLE
请教一下，是如何保证与ES的最新文档同步的？

### ISSUE THREAD

**Issue by thihy** [GavinFoo/elasticsearch-definitive-guide#11]
我看了一下，是直接在原文上编辑的，很疑惑，如何自动同步ES的最新文档哈？

**Comment by meteormatt** [comment]
:+1: 
同问
http://www.v2ex.com/t/116261

**Comment by GavinFoo** [comment]
目前只是按照进度先统一翻译完 然后对比fork的文档仓库再做一次修改，不知道两位有什么好的工具吗？

**Comment by meteormatt** [comment]
我也不知道什么好工具.
但是感觉结构和官方的都不一样, 这样比较难同步.
https://github.com/elasticsearch/elasticsearch-definitive-guide
感觉这里的只是gitbook的项目, 并没有原文.

**Comment by cooniur** [comment]
@meteormatt 
我也觉得应当与官方文档格式同步, 这样比较好对比翻译. 当有更新时, 也会比较好处理.

原文都在里面, 比如这里: https://github.com/elastic/elasticsearch-definitive-guide/blob/master/010_Intro/05_What_is_it.asciidoc

**Comment by meteormatt** [comment]
@cooniur 是的. 那里是`asciidoc`, 这里都是转换好的`html`

**Comment by cooniur** [comment]
@meteormatt 嗯, 我的意思就是在"源代码"级别上做翻译比较好.

**Comment by GavinFoo** [comment]
@meteormatt   @cooniur 
我这里之所以转换了一下是因为gitbook早期的时候并不支持asciidoc，而且asciidoc当时也不能直接在github上查看所以就为了发布方便就选择了markdown, 至于同步目前使用的是我克隆的仓库和官方仓库diff的方法

**Comment by thihy** [comment]
原来有一个工具，可以自动识别HTML标签的。现在记不得这个网站了。等我想起来，再回复一下。

**Comment by thihy** [comment]
可以看看这个网址：http://zanata.org/  试过，还比较好用的
