### ISSUE TITLE
词语错了

### ISSUE THREAD

**Issue by andykai** [GavinFoo/elasticsearch-definitive-guide#20]
1.分布式集群-横向扩展的最后一句话中：
原语句：我们一共有6个节点（3个主分片和3个从分片），因此最多可以扩展到6个节点，每个节点上有一个分片，这样每个分片都可以使用到所在节点100%的资源了。
问题：我们一共有6个节点，这里的节点应该是分片才对吧。

2.搜索-空白搜索-timeout
原语句：例如10、"10ms"（10毫秒）或者"1s"（1分钟）：
问题：1s 应该是1秒吧

3.搜索-多索引，多类型
原语句：第二段中   当我们没有特别指定一个所以或者类型的时候
问题：所以->索引

原语句：表格中  /gb,us/user,tweet/_search	搜索索引user以及tweet中类型gb and us内的所有文档
问题： 后面的描述语句中 use,tweet和gb,us的定义说反了

**Comment by GavinFoo** [comment]
fixed  非常感谢！
