### ISSUE TITLE
这里是不是有点错误?

### ISSUE THREAD

**Issue by veryplay** [GavinFoo/elasticsearch-definitive-guide#3]
了解搜索
--> 8 line
Elasticsearch使用Lucene作为内部引擎，但是在你使用它做全文搜索时，只需要使用统一开发好的API即可，请不需要了解其背后复杂的Lucene的运行原理。

"请不需要了解其背后复杂的Lucene的运行原理。" 是不是应该改为 "并不需要了解其背后复杂的Lucene的运行原理。"

**Comment by GavinFoo** [comment]
fixed
